apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webcolor
  namespace: argocd
  labels: 
    curso: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/leosimao88/web-page-deploy.git
    path: k8s
    targetRevision: HEAD
    directory:
      recurse: true
      include: '{nginx/*,webcolor/*}'
  destination:
    server: https://kubernetes.default.svc
    namespace: webcolor
  info:
    - name: Projeto
      value: "Curso de GitOps"